name: Jalaali_Example
description: A flutter package to make working with solar date easier. You can convert dates to solar dates and manipulate those by using this package in your app.
version: 0.1.0
author: Moein Hosseini <mrdimaan@tuta.io>

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  jalaali:
    path: ../

flutter:
