name: jalaali
description: A flutter package to help .
version: 0.0.1
author: Moein Hosseini <mrdimaan@tuta.io>
homepage: https://github.com/mrdimaan/flutter_jalaali

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: